apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  ports:
    - port: 9090
      nodePort: 30000
  selector:
    app: prometheus
    tier: backend
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pv-claim
  labels:
    app: prometheus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    name: prometheus-config
data:
 prometheus.yml: |-
  global:
    scrape_interval: 5s
    evaluation_interval: 5s
  alerting:
    alertmanagers:
    - static_configs:
      - targets:
   #rule_files:
   # - "first_rules.yml"
   # - "second_rules.yml"

  scrape_configs:
    - job_name: 'prometheus'
    #metrics default path is /metrics
      static_configs:
      - targets: ['localhost:9090']

    - job_name: 'node1'
      static_configs:
      - targets: ['192.168.99.101:9100']
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: prometheus
  labels:
    app: prometheus
    tier: backend
spec:
  selector:
    matchLabels:
      app: prometheus
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: prometheus
        tier: backend
    spec:
      containers:
      - image: prom/prometheus:latest
        name: prometheus
        args:
        - "--config.file=/etc/prometheus/prometheus.yml"
        ports:
        - containerPort: 9090
          name: prometheus
        volumeMounts:
        - name: prometheus-persistent-storage
          mountPath: /prometheus
        - name: prometheus-config
          mountPath: /etc/prometheus/
      volumes:
      - name: prometheus-persistent-storage
        persistentVolumeClaim:
          claimName: prometheus-pv-claim
      - name: prometheus-config
        configMap:
          name: prometheus-config